use_frameworks!

platform :ios, '8.0'

target 'LGHomeModule_Example' do
  pod 'LGHomeModule', :path => '../'
  pod 'LGMacroAndCategoryModule', :path => '../../LGMacroAndCategoryModule'
  pod 'LGCommonUIModule', :path => '../../LGCommonUIModule'
  pod 'LGPlayerModuleCategory', :path => '../../LGPlayerModuleCategory'

  target 'LGHomeModule_Tests' do
    inherit! :search_paths
    
  end
end
