use_frameworks!

platform :ios, '8.0'

target 'LGDataHandleMoudle_Example' do
  pod 'LGDataHandleMoudle', :path => '../'

  target 'LGDataHandleMoudle_Tests' do
    inherit! :search_paths

    
  end
end
