use_frameworks!

platform :ios, '8.0'

target 'LGPlayerModule_Example' do
  pod 'LGPlayerModule', :path => '../'
  pod 'LGCommonUIModule', :path => '../../LGCommonUIModule'
  pod 'LGMacroAndCategoryModule', :path => '../../LGMacroAndCategoryModule'
  pod 'LGDLNAModule', :path => '../../LGDLNAModule'


  target 'LGPlayerModule_Tests' do
    inherit! :search_paths

    
  end
end
