use_frameworks!

platform :ios, '8.0'

target 'LGMacroAndCategoryModule_Example' do
  pod 'LGMacroAndCategoryModule', :path => '../'

  target 'LGMacroAndCategoryModule_Tests' do
    inherit! :search_paths

    
  end
end
