# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '006---FBKVOController探索' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 006---FBKVOController探索

pod 'KVOController'
  target '006---FBKVOController探索Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '006---FBKVOController探索UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
